### PR TITLE
Add support for python 3.11

### PR DESCRIPTION
**Pull request by njooma**
This PR updates all our dependencies and makes us compatible with python 3.11

### CODE REVIEW

**Comment by njooma** [comment]
@maximpertsov License finder is failing on protobuf again, which [hasn't changed since 2018](https://github.com/protocolbuffers/protobuf/blob/main/LICENSE). I can't remember how it was fixed last time

**Comment by maximpertsov** [comment]
> @maximpertsov License finder is failing on protobuf again, which [hasn't changed since 2018](https://github.com/protocolbuffers/protobuf/blob/main/LICENSE). I can't remember how it was fixed last time

That's odd, [we explicitly approved this dependency before](https://github.com/viamrobotics/viam-python-sdk/pull/148#issuecomment-1261261099) but it looks like that entry was removed from `doc/dependency_decision.yml`

**Comment by njooma** [comment]
Yup I just found that PR myself. I went ahead and updated the license file but I'm very confused as to where that PR went...

**Review by stuqdog — APPROVED** [review]

**Comment by stuqdog** [comment]
lgtm, I assume this was tested with `3.11`?

**Comment by njooma** [comment]
Yes it has been tested with python 3.11, but I setup our test suite to make it more explicit. Checkout the manual run here: https://github.com/viamrobotics/viam-python-sdk/actions/runs/3491998954

**Review by stuqdog — APPROVED** [review]

**Pull request merged**
