### PR TITLE
rc-0.21.0

### PR DESCRIPTION
**Pull request by njooma**
Let's merge in our breaking changes!!

### CODE REVIEW

**Review by stuqdog — APPROVED** [review]
Reviewed all the individual commits already so just did a super cursory eye over, looks good to me!

**Review by purplenicole730 — APPROVED** [review]
Woot woot! 🎉 (same as Ethan, took a quick glance)

**Comment by njooma** [comment]
@viamrobotics/fleet-management `camera.get_image` was changed! What to do?

**Comment by DTCurrie** [comment]
> @viamrobotics/fleet-management `camera.get_image` was changed! What to do?

Start here, might be slightly outdated now that the code samples have moved to the `ui` svelte project, but it should be ok: https://viam.atlassian.net/wiki/spaces/ENG/pages/231473156/Code+Samples

**Comment by njooma** [comment]
@DTCurrie Thanks! Took a look, seems like we don't have to do anything because the return type isn't specified in the python examples

**Pull request merged**
