### PR TITLE
APP-1286 - Code samples workflow fix paths

### PR DESCRIPTION
**Pull request by Kschappacher**

### CODE REVIEW

**Review by maximpertsov — APPROVED** [review]

**Review by njooma — CHANGES_REQUESTED** [review]
wow what timing can you take a look at my comments from the other PR that was merged in like 1sec after I commented so there was no way you could've seen those comments? They were just comments tho so feel free to be like "nah" and then I'll approve this one lol

https://github.com/viamrobotics/viam-python-sdk/pull/227

**Comment by Kschappacher** [comment]
> wow what timing can you take a look at my comments from the other PR that was merged in like 1sec after I commented so there was no way you could've seen those comments? They were just comments tho so feel free to be like "nah" and then I'll approve this one lol
> 
> #227

Wow thats wild timing. For ubuntu latest we are doing the same thing for our comment workflow on rdk so im good with keeping that pattern here. To link to the fleet team maybe we link to our jira board? Im down for suggestions for how to reach out to us.

**Comment by njooma** [comment]
Ya I wasn't sure. the sdk-netcode team has an actual GitHub team that we can tag @viamrobotics/sdk-netcode so I was thinking maybe something like that? but it doesn't seem that fleet management has that setup?

**Comment by Kschappacher** [comment]
> Ya I wasn't sure. the sdk-netcode team has an actual GitHub team that we can tag @viamrobotics/sdk-netcode so I was thinking maybe something like that? but it doesn't seem that fleet management has that setup?

I added a  @viamrobotics/fleet-management team in github and changed the comment to reflect this

**Review by njooma — APPROVED** [review]

**Pull request merged**
