### PR TITLE
RSDK-4089: change camera api return types

### PR DESCRIPTION
**Pull request by purplenicole730**
Return ViamImage object when using camera component.

Tested using laptop's webcam!
`mycam get_image return value: <viam.media.video.ViamImage object at 0x102f3de10>`
tmp4wghpj1b

### CODE REVIEW

**Comment by benjirewis** [comment]
Hmm this seems good to me, but I worry I don't have enough context to review here. Will bring up in weekly sync whether Maxim and I should continue to be in the `sdk-netcode` group (and whether that should be renamed).

**Comment by purplenicole730** [comment]
@bazile-clyde Could someone from your team also provide a PR so that we're certain we're doing everything correctly?

**Comment by purplenicole730** [comment]
> > @bazile-clyde Could someone from your team also provide a PR so that we're certain we're doing everything correctly?
> 
> Provide a PR for what exactly? Are you asking us to review _this_ PR, or create our own PR for something?

Oh oops, sorry about that! I meant review this PR 😅

**Comment by bazile-clyde** [comment]
> > > @bazile-clyde Could someone from your team also provide a PR so that we're certain we're doing everything correctly?
> > 
> > 
> > Provide a PR for what exactly? Are you asking us to review _this_ PR, or create our own PR for something?
> 
> Oh oops, sorry about that! I meant review this PR 😅

No worries! I can review it. Adding myself now.

**Review by njooma — APPROVED** [review]
Nice

**Pull request merged**
