### PR TITLE
RSDK-4578: Python SDK Base Properties

### PR DESCRIPTION
**Pull request by martha-johnston**
Update python SDK to include new base property `wheel_circumference_meters`

Note to reviewers: I am not sure if there's something I have to do to specifically update this PR to use the most recent API changes? I'm seeing some errors which I believe are because it's not referencing the most recent version of API. 

Edit: It passed all the checks though so maybe that was just a local issue

### CODE REVIEW

**Comment by stuqdog** [comment]
@martha-johnston you are correct, it looks like we don't have the latest in yet. I think tests are passing because we don't have any tests that specifically would check for this, but I wouldn't expect a user to have success with it as-is.

@njooma looks like we haven't updated protos in python in a while, are you aware of any changes that need to be implemented before we can do so?

**Comment by maximpertsov** [comment]
> @martha-johnston you are correct, it looks like we don't have the latest in yet. I think tests are passing because we don't have any tests that specifically would check for this, but I wouldn't expect a user to have success with it as-is.
> 
> @njooma looks like we haven't updated protos in python in a while, are you aware of any changes that need to be implemented before we can do so?

I pulled in proto changes for typescript recently and saw that [the motion services had breaking changes](https://github.com/viamrobotics/viam-typescript-sdk/pull/155)

**Comment by njooma** [comment]
> @martha-johnston you are correct, it looks like we don't have the latest in yet. I think tests are passing because we don't have any tests that specifically would check for this, but I wouldn't expect a user to have success with it as-is.
> 
> 
> 
> @njooma looks like we haven't updated protos in python in a while, are you aware of any changes that need to be implemented before we can do so?

Yup, there are breaking data changes as well. Tagged you @stuqdog and @8ashar to snag the latest data updates: [comment](https://github.com/viamrobotics/viam-python-sdk/pull/373#issuecomment-1669772251)

**Comment by martha-johnston** [comment]
Just want to follow up here, is there something I specifically need to do related to these breaking changes in this PR in order to update to the latest proto?

**Comment by njooma** [comment]
@martha-johnston I updated the protos. If you rebase from main, you should be able to get all the new protos and accurately test your code.

**Comment by martha-johnston** [comment]
@maximpertsov @cheukt should be good to go for review now! all the protos are updated and tests pass

**Review by maximpertsov — APPROVED** [review]

**Review by cheukt — APPROVED** [review]
LGTM

**Pull request merged**
