### PR TITLE
use poetry cache in CI

### PR DESCRIPTION
**Pull request by abe-winter**
## What changed
- add `cache: poetry` param to setup-python action
## Why
Faster builds
## Comparison
I did a run [here](https://github.com/viamrobotics/viam-python-sdk/actions/runs/9518864325) and then reran again after it succeeded (to get cache).

Speedup is about 40 seconds for the slowest job (2:30 -> 1:50).

Before and after:
before-after

### CODE REVIEW

**Review by njooma — APPROVED** [review]
Surprised that "Install Poetry" works before "Setup python"

I wanted to test if the min/max requirements worked with the cache and I guess the answer is yes! Thanks for doing the test for me

**Comment by abe-winter** [comment]
I'm not actually sure the min version step is getting cached

times are:

run | install | min version
initial | 45s | 26
cached | 2s | 26

not sure, but guessing it's not using the requirements file as part of the cache key? (but not sure that should matter; would have thought each matrix job has its own cache)

**Comment by abe-winter** [comment]
switching to `pipx install poetry` per [their example](https://github.com/actions/setup-python/blob/main/docs/advanced-usage.md#caching-packages) seems to gain a few seconds (slowest cached job is now 1:20-1:30 vs 1:52 before)

also the min requirements step is installing pillow and it is not available as a wheel for new python I think -- if not required anymore, that seems to be the limiting step now

**Comment by njooma** [comment]
We still need Pillow in our tests because we have PIL-specific utilities

**Pull request merged**
