### PR TITLE
RSDK-5390 - [BREAKING] MoveOnGlobe definition change

### PR DESCRIPTION
**Pull request by nicksanford**
[Ticket](https://viam.atlassian.net/browse/RSDK-5390)
Depends on:
RDK: https://github.com/viamrobotics/rdk/pull/3303
Previous SDK change: https://github.com/viamrobotics/viam-python-sdk/pull/500
API change: https://github.com/viamrobotics/rdk/pull/3303

### CODE REVIEW

**Comment by nicksanford** [comment]
@njooma this PR depends on the latest api definition (`v0.1.238`+). How do I go about updating that?

**Comment by njooma** [comment]
@nicksanford The new protos are in this PR: https://github.com/viamrobotics/viam-python-sdk/pull/505

You can test using this. If you want me to merge it in, LMK and we can do that too

**Comment by nicksanford** [comment]
@njooma If possible I'd like to get the protos & this PR merged this week so the python SDKS are compatible with the next stable version of viam server.

**Comment by njooma** [comment]
@nicksanford You'll have to pull in the changes from the [automated PR](https://github.com/viamrobotics/viam-python-sdk/pull/505) in order to get the updated protos in order for this PR to pass tests, and then we can merge it all in this week

**Review by njooma — APPROVED** [review]
LGTM! thanks

**Pull request merged**
