### PR TITLE
RSDK-7747: Add SetRPM to python SDK

### PR DESCRIPTION
**Pull request by martha-johnston**
actual changes are in the first commit, second is autogenerated files

will merge API changes that this depends on later today

### CODE REVIEW

**Comment by martha-johnston** [comment]
was having issues with the auto generated protos, resolved by committing everything _except_ `app_grpc.py`. when that file is generated, there is a new method `RenameKey` that causes all of the app client tests to fail. I can't find a ticket about adding `RenameKey` anywhere so I don't know what that's about, but is it alright to just include protos related to my change?

**Review by njooma — APPROVED** [review]
Approving, but I'm going to try and merge some changes into main to help get your proto stuff unblocked, so I'll comment again when that's ready

**Comment by martha-johnston** [comment]
> Approving, but I'm going to try and merge some changes into main to help get your proto stuff unblocked, so I'll comment again when that's ready

thanks sounds good

**Comment by martha-johnston** [comment]
thanks for the help @njooma

**Pull request merged**
